### ISSUE TITLE
Width of image doesn't fit.

### ISSUE THREAD

**Issue by CGraabaek** [KilianB/NetflixViewingActivityVisualizer#3]
I tried only making one with data from 2018. 
It seems from-to dates are missing, and the width doesn't fit. 

Image is attached: 

![netflixinfographics](https://user-images.githubusercontent.com/6660378/50058096-e8cb1180-0173-11e9-9f0f-e47cf61caf98.png)

Are there any settings i seem to have missed?

**Comment by CGraabaek** [comment]
Changing line 505 to this 
`png(outputPath, width = 15, height = 25, units = "in", res = 500, type = "cairo")`

fixed the problem.

**Comment by KilianB** [comment]
I'll take a look at it tomorrow. thanks
